# 源代码仓库: https://github.com/IzzelAliz/Arclight
# 提交反馈/错误报告: https://github.com/IzzelAliz/Arclight/issues
# 
# 
# 配置文件版本号，请勿编辑
"_v"=1
# 异步捕获相关设置
# Async Catcher 共有四种模式
# NONE - 保持在当前线程执行
# DISPATCH - 不阻塞地发布到主线程
# BLOCK - 发布到主线程并等待结果
# EXCEPTION - 抛出异常
async-catcher {
    defaultOperation=block
    # 是否在 debug 日志中打印堆栈信息
    dump=true
    overrides {}
    warn=true
}
compatibility {
    entity-property-overrides {}
    # 额外运行逻辑的维度类名
    # 如果有模组世界/功能运行不正常，尝试在日志中搜索和 [EXT_LOGIC] 有关的对应类名并添加
    extra-logic-worlds=[
        "com.example.mod.ExtraLogicWorld",
        "xyz.nucleoid.fantasy.RuntimeWorld"
    ]
    # true - 将 ModLoader 权限查询请求转发至 Bukkit
    # false - 不启用权限转发
    # reverse - 将 Bukkit 玩家权限查询请求转发至 ModLoader
    forward-permission=true
    # 阻止插件从你的模组加载器加载Kyori Adventure。
    # 这只是一个兼容性选项，且仅现在存在。未来会以更完善的机制取缔，
    isolate-adventure-from-modloader=false
    # 非法访问指一个插件加载了自身未声明依赖（depend）或软依赖（soft-depend）的其他插件中的类。
    # 当设置了某个包名时，将不会对以此包名为前缀的类尝试任何非法访问。
    # 这在发生类加载问题时尤其有用。
    # 请注意：这可能导致依赖非法访问的插件失效。
    isolate-plugin-class-loaders=[
        "com.example.mod.package.aaaa"
    ]
    material-property-overrides {}
    # 为模组的维度创建符号链接
    # 推荐启用以增强插件交互兼容性
    # 变更此设置会导致模组世界名称变化，可能造成依赖世界名称的插件数据丢失
    # 参见 https://github.com/IzzelAliz/Arclight/wiki/World-Symlink
    symlink-world=false
    # 用户名合法检查正则表达式，留空为使用原版检查
    # 如果需要允许中文字符可以使用
    # valid-username-regex = "^[ -~\p{sc=Han}]{1,16}$"
    # 如果允许任何用户名可以使用
    # valid-username-regex = ".+"
    valid-username-regex=""
}
# 这些实验性设置可能可以提高兼容性或功能性。
# 如果你决定使用这些设置，请汇报任何你遇到的问题。
experimental {
    # 此设置设计来提供TerraBlender的多世界支持。
    # 然而他也可以用于为多世界支持添加更多可用世界。
    # 不建议创建mod特定的维度。这种情况可能不受支持。
    # Bukkit中，区块生成器可以可选的依赖于原版生成器的结果，
    # 而生物群系提供器会完全覆盖群系提供。
    # 如果你想要使用已加载的世界生成配置(LevelStem)，
    # 为对应世界使用CUSTOM环境，会令Arclight为此世界使用'bukkit:<世界名>'的生成配置。
    # 此世界生成配置可以由数据包提供的。
    # 设置后，来自原世界中的世界生成配置信息会被忽略。
    # 这也会忽略WorldType设置。就是可以通过mv create的-t设置的那个。
    # 这些应当均可以在数据包中指定。
    # 为一个已生成的世界配置此设置可能会导致世界生成撕裂。
    replaceable-base-world-generator=false
}
# 语言/国际化相关设置
locale {
    current="ja_jp"
    fallback="en_us"
}
# 服务端优化相关设置
optimization {
    cache-plugin-class=true
    # 关闭用于升级存档数据的 DataFixerUpper 系统
    # 这将可能加快启动速度和地图加载速度，并减少 80-200mb 的内存占用
    # Arclight 及其开发者不对任何数据丢失或损害负责
    # 请不要在生产环境中使用
    disable-data-fixer=false
    # 实体目标选择器的更新间隔
    # 数值越高消耗资源越少
    # 导致实体更改目标速度变慢
    goal-selector-update-interval=2
    # 是否使用Spigot Activation Range和Tracking Range优化
    use-activation-and-tracking-range=true
}
velocity {
    # 启用 Velocity 的玩家信息转发支持
    enable=false
    # Velocity 玩家信息转发使用的密钥
    secret=""
}
