plugins {
    id 'architectury-plugin'
}

architectury {
    common(rootProject.ext.supportedPlatforms)
}

loom {
    accessWidenerPath = file('src/main/resources/arclight.accesswidener')
    mixin {
        useLegacyMixinAp = true
        defaultRefmapName = 'arclight-common-refmap.json'
        add sourceSets.main, 'arclight-common-refmap.json'
    }
}

configurations {
    mixinProcessorSupport
}

dependencies {
    modImplementation libs.fabric.loader

    compileOnly rootProject.ext.generatedSpigot

    implementation libs.izzel.tools
    implementation libs.arclight.api
    implementation libs.mixin.tools
    annotationProcessor libs.mixin.tools
    mixinProcessorSupport libs.gson
    mixinProcessorSupport 'com.google.guava:guava:33.5.0-jre'
    mixinProcessorSupport libs.asm.util
    mixinProcessorSupport libs.asm.tree

    // spigot
    implementation libs.spigot.api
    implementation libs.jline
    implementation libs.terminalconsoleappender
    implementation libs.specialsource
    implementation libs.log4j.jul
    implementation libs.bungeecord.serializer
    implementation libs.mysql.connectorj
    implementation libs.snakeyaml

    implementation project(':i18n-config')
}

compileJava {
    options.compilerArgs << '-XDignore.symbol.file' << '-XDenableSunApiLintControl'
    options.annotationProcessorPath = configurations.annotationProcessor + configurations.mixinProcessorSupport
    options.encoding = 'UTF-8'
}
