name: 🐞 错误报告表格
description: 通过填写表格来报告错误
labels: [ "Status: Triage" ]

body:
  - type: markdown
    attributes:
      value: |
        Arclight是混合服务端，不可避免地存在一些问题，遇到问题请先向Arclight反馈，不要去烦模组/插件作者

  - type: checkboxes
    id: pre-requirements
    attributes:
      label: 我已经做过以下尝试：
      description: 请进行如下尝试，以免无效反馈
      options:
        - label: 我正在使用最新的[Arclight构建版本](https://arclight.izzel.io/)
          required: true
        - label: 我已经阅读[常见问题](https://wiki.izzel.io/s/arclight-docs/doc/faq-ApcZ25PXVT)及[常见故障解决方案](https://wiki.izzel.io/s/arclight-docs/doc/troubleshooting-1Ay2vsmIrn)，无法解决我遇到的问题
          required: true
        - label: 我已经搜索过现有Issues，没有相同的问题
          required: true
        - label: 我使用的模组和（或）插件支持我使用的Minecraft版本
          required: true
        - label: 我已为所有模组和（或）插件安装所需的依赖
          required: true
        - label: 我已把所有模组和（或）插件更新至最新版
          required: true
        - label: |
            此问题不可在Spigot服务端复现  
            （模组问题视为无法在Spigot复现）
          required: true
        - label: |
            此问题不可在对应Mod加载器服务端（Forge/NeoForge/Fabric）复现  
            （插件问题视为无法在模组端复现）
          required: true

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft版本
    validations:
      required: true

  - type: input
    id: arclight-version
    attributes:
      label: Arclight版本
      description: 在Arclight服务端启动时会输出版本
      placeholder: 如：arclight-1.15.2-1.0.3-SNAPSHOT-9455d03
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: 操作系统版本
      description: 操作系统版本
      placeholder: 如：Windows 11或Ubuntu 24.04 arm64（如果架构不是amd64，请标注）
    validations:
      required: true

  - type: textarea
    id: java-version
    attributes:
      label: Java版本
      description: 在命令行中使用`java --version`的输出
      placeholder: |
        openjdk 21.0.5 2024-10-15 LTS
        OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS)
        OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode, sharing)
    validations:
      required: true

  - type: textarea
    id: related-mods
    attributes:
      label: 相关模组和（或）插件的名称及版本
      description: |
        输入`/plugins`命令可获取插件列表  
        Forge上使用`/forge mods`命令得到模组列表  
        Fabric和NeoForge的模组列表会在服务器启动时输出  
        排除无关的模组和插件有助于问题及时解决，如果它和任何模组/插件无关，请留空
      placeholder: |
        模组: 
          Mod A (1.2)
          Mod B (3.14)
        
        插件: 
          Plugin A (2.3.3)
          Plugin B (2.7)
      render: raw
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: 错误描述
      description: |
        请尽可能详细描述问题，如果不知道如何描述，可以参考：  
        出现了什么问题？  
        它应该是怎么样的？  
        是否做过解决此问题的尝试？如果有，是怎么做的，结果如何？
      placeholder: 详细描述它为什么是一个错误……
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 复现步骤
      placeholder: |
        1. 安装……
        2. 进入服务器后……
        3. ……

  - type: textarea
    id: logs
    attributes:
      label: 服务器日志
      description: |
        `logs/latest.log`文件中的内容就是服务器日志  
        服务器关闭后，将日志文件拖拽至输入框上传  
        或上传至在线剪贴板网站（如[mclo.gs](https://mclo.gs/)）提交后将链接附在下方  
        **请勿直接复制粘贴日志文本**
      placeholder: 日志链接，或将日志文件拖到此处上传

  - type: input
    id: pack-to-reproduce
    attributes:
      label: 复现用服务端压缩包下载链接
      description: |
        如果模组或插件太多，可以打包服务端并上传到网盘，便于开发者下载测试  
        如果是整合包，也可以贴上整合包的原帖链接  
