name: ðŸž Bug Report Form
description: Fill a Form for bug reporting
title: "[Bug Report]: "
labels: ["triage"]

body:
  - type: markdown
    attributes:
      value: >-
        Before reporting an error, please ensure that there is no similar existing one report that
        <br>Please fill in the following content completely.
        <br>At Last, Thank you for your reporting.
  - type: input
    id: version
    attributes:
      label: Arclight Version
      description: Versions are printed when Arclight is starting, for example arclight-1.15.2-1.0.3-SNAPSHOT-9455d03
    validations:
      required: true

  - type: input
    id: confirm
    attributes:
      label: Are you running the latest development version?
      description: >-
        Latest development build can be found at https://github.com/IzzelAliz/Arclight/actions
        <br>The issue you are reporting may be fixed
        <br>If you are not running latest dev version, explain why
      placeholder: "Example: Yes|No, Reason Here"
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Java Version | Operating System
      description: Type `java -version` in your console
      placeholder: "Exampleï¼šJava-Openjdk_11(Hotspot) | Windows Server 2019"
    validations:
      required: true

  - type: textarea
    id: related
    attributes:
      label: The Name and Version of Related Mod/Plugins 
      description: Run `/plugins` and `/forge mods` in your server to get it.
      value: >-
        Mods:     
        Plugins:
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        Please include as much information as possible. 
        <br>For the description, assume we have no idea how mods work, 
        be as detailed as possible and include a step by step reproduction. 
        <br>It is recommended you try to reproduce the issue you are having yourself with as few mods as possible. 
        <br>The clearer the description, the higher the report processing priority

      placeholder: "What Happens"
    validations:
      required: true

  - type: textarea
    id: step
    attributes:
      label: Step to reproduce
      value: >-
        1. Install something
        2. ...
        3. ....
     
  - type: dropdown
    attributes:
      label: Reproducible in Forge
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Reproducible in Spigot
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: >-
        Logs can be found in /logs/latest.log
        After server is stopped, paste it to https://paste.ubuntu.com/
        
        If you have trouble using a pastebin, paste these codes to {ERROR LOG] and fill it
      value: >-
        Logs link:
        If you can not use any Paste Service, replace [Logs] with your paste.
        <details><pre>
        [Logs]
        </pre></details>