modLoader="javafml"
loaderVersion="[2,)"
license="GNU GENERAL PUBLIC LICENSE Version 3"

[[mods]]
modId="arclight"
version="${version}"
displayName="Arclight Mod"
displayTest="IGNORE_SERVER_VERSION"
credits="lona,夜幕"
authors="IzzelAliz"
description='''
    Arclight bukkit layer for NeoForge
    '''

[[mixins]]
config="mixins.arclight.core.json"

[[mixins]]
config="mixins.arclight.bukkit.json"

[[mixins]]
config="mixins.arclight.neoforge.json"

[[mixins]]
config="mixins.arclight.impl.optimization.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
