plugins {
    id 'architectury-plugin'
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

dependencies {
    implementation libs.fabric.loader
    implementation libs.fabric.api

    implementation libs.izzel.tools
    implementation libs.arclight.api
    implementation libs.mixin.tools
    annotationProcessor(libs.mixin.tools) { transitive = false }

    implementation(libs.bundles.spigot.shade) { transitive = false }
    shadowBundle(libs.bundles.spigot.shade) { transitive = false }
    implementation rootProject.ext.generatedSpigot
    shadowBundle rootProject.ext.generatedSpigot

    implementation libs.fabric.permissions.api
    include libs.fabric.permissions.api

    // XXX: for compiling (arclight-api): FabricArclightServer#registerForgeEvent
    compileOnly("net.minecraftforge:eventbus:4.0.0") { transitive = false }

    implementation(project(':i18n-config')) { transitive = false }

    common(project(path: ':arclight-common')) { transitive = false }
    shadowBundle(project(path: ':arclight-common', configuration: 'transformProductionFabric')) { transitive = false }
    common(project(':bootstrap')) { transitive = false }
    shadowBundle(project(':bootstrap')) { transitive = false }
}

compileJava {
    if (!project.hasProperty('enableMixinAp')) {
        options.compilerArgs << '-proc:none'
    }
}

tasks.register('fabricMappings', Copy) {
    destinationDir = file('build/fabric_mappings')
    from(arclight.mappingsConfiguration.bukkitToFabric) {
        rename { name -> 'bukkit_srg.srg' }
    }
    from(arclight.mappingsConfiguration.bukkitToNeoForge) {
        rename { name -> 'bukkit_moj.srg' }
    }
    from(arclight.mappingsConfiguration.bukkitToFabricInheritance) {
        rename { name -> 'inheritanceMap.txt' }
    }
}

project.sourceSets.main.output.dir file('build/fabric_mappings'), builtBy: tasks.fabricMappings

processResources {
    def ver = "${project.version}+$gitHash"
    inputs.property 'version', ver

    filesMatching('fabric.mod.json') {
        expand 'version': ver
    }
}

jar {
    archiveClassifier = 'raw'
}

shadowJar {
    dependsOn jar
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))

    exclude 'architectury.common.json'

    configurations = [project.configurations.shadowBundle]
    archiveClassifier = null
}

tasks.register('srgJar', Jar) {
    from(tasks.shadowJar.outputs.files.collect { it.isDirectory() ? it : zipTree(it) }) {
        include 'io/izzel/**'
        exclude 'io/izzel/arclight/common/mixin/**'
        exclude 'io/izzel/arclight/forge/mixin/**'
    }
    archiveClassifier.set('srg')
    dependsOn shadowJar
}

sourcesJar {
    def commonSources = rootProject.ext.commonProject.sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}
